apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-red
spec:
  selector:
    matchLabels:
      app: echo-red
  replicas: 3
  template:
    metadata:
      labels:
        app: echo-red
    spec:
      containers:
        - name: app
          image: 970805265562.dkr.ecr.us-west-2.amazonaws.com/colorteller:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: COLOR
              value: '<html style="background-color: red;"></html>'
            - name: SERVER_PORT
              value: "8080"
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: echo-red
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: echo-red
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo-red
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: my-group
    alb.ingress.kubernetes.io/group.order: "1"
spec:
  rules:
    - http:
        paths:
          - path: /red
            backend:
              serviceName: echo-red
              servicePort: 80
          - path: /color
            backend:
              serviceName: echo-red
              servicePort: 80