apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048
spec:
  selector:
    matchLabels:
      app: game-2048
  replicas: 3
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      containers:
        - name: app
          image: alexwhen/docker-2048
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: game-2048
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: game-2048
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: game-2048
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: my-group
    alb.ingress.kubernetes.io/group.order: "3"
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: game-2048
              servicePort: 80
